all: *.java
	javac -d bin Lab2.java

fig1: *.java
	javac -d bin Lab2.java
	java -cp bin Lab2 -k8 -w12 -h12 < fig1.txt

fig2: *.java
	javac -d bin Lab2.java
	java -cp bin Lab2 -k8 -w12 -h12 < fig2.txt

clean:
	rm -rf bin/*
